# Docker Compose פשוט לפיתוח
version: '3.8'

services:
  # מסד נתונים PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: parkbnb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: parkbnb_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MailHog לבדיקת מיילים (אופציונלי)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: parkbnb-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    profiles: ["tools"]

  # Adminer לניהול DB (אופציונלי)
  adminer:
    image: adminer:latest
    container_name: parkbnb-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on: [postgres]
    profiles: ["tools"]

volumes:
  postgres_data:
